//* Fake data product for you
const allForYou = [
    {
        id: 1,
        image: "for-you/for-you-1",
        title: "Tai Nghe Bluetooth True Wireless TaoTronics SoundLiberty 53 (TT-BH053) - Hàng Chính Hãng",
        sold: "26",
        price: "699.000",
        discount: "44",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 2,
        image: "for-you/for-you-2",
        title: "Tai nghe Xiaomi Bluetooth True Wireless Earphones 2 Basic Xiaomi BHR4089GL - Hàng Chính Hãng",
        sold: "375",
        price: "804.000",
        discount: "49",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 3,
        image: "for-you/for-you-3",
        title: "Tai Nghe True Wireless Earbuds SoundPeats Mac, thời gian sử dụng 60 giờ, chống nước IPX7, bluetooth v5.0 - Hàng chính hãng",
        sold: "1000+",
        price: "609.000",
        discount: "44",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 4,
        image: "for-you/for-you-4",
        title: "Tai Nghe True Wireless REROKA-CYBORG Bluetooth V5.0, đeo êm tai, âm thanh sống động, hộp sạc có màn hình led hiển thị - Hàng chính hãng",
        sold: "207",
        price: "367.000",
        discount: "26",
        oneLine: false,
        sale: true,
        refund: true,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 5,
        image: "for-you/for-you-5",
        title: "Tai nghe bluetooth Remax TWS-28 - Hàng chính hãng",
        sold: "21",
        price: "599.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 6,
        image: "for-you/for-you-1",
        title: "Tai Nghe Bluetooth Nhét Tai PKCB True Wireless - Hàng Chính Hãng VN/A",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: true,
        ship: false,
        rate: true,
        star: 4,
    },
    {
        id: 7,
        image: "for-you/for-you-7",
        title: "Phấn Phủ Kiềm Dầu Dạng Bột Khoáng Innisfree No Sebum Mineral Powder 5g",
        sold: "1000+",
        price: "120.000",
        discount: "20",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 8,
        image: "for-you/for-you-8",
        title: "Phấn Phủ SHISEIDO BABY POWDER PRESSED Dạng Nén 50g JAPAN",
        sold: "26",
        price: "142.999",
        discount: "44",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 9,
        image: "for-you/for-you-9",
        title: "Phấn phủ dạng nén Eglips Oil Cut Powder Pact 9g Thành Phần Tự Nhiên Che Khuyết Điểm, Kiềm Dầu Tốt, Thân Thiện Với Da, Không Gây Kích Ứng",
        sold: "113",
        price: "135.000",
        discount: "50",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 10,
        image: "for-you/for-you-10",
        title: "Apple iPhone 11",
        sold: "1000+",
        price: "11.250.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 11,
        image: "for-you/for-you-11",
        title: "Apple iPad 10.2-inch (9th Gen) Wi-Fi, 2021",
        sold: "779",
        price: "9.150.000",
        discount: "17",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 12,
        image: "for-you/for-you-12",
        title: "Apple iPad Pro 12.9 - inch M1 Wi-Fi + Cellular, 2021",
        sold: "34",
        price: "27.570.000",
        discount: "11",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 13,
        image: "for-you/for-you-13",
        title: "Lốc 4 lon Bia Tuyết - Edelweiss 330ml/lon",
        sold: "1000+",
        price: "81.000",
        discount: "27",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },

    {
        id: 14,
        image: "for-you/for-you-14",
        title: "Thùng 24 Lon Bia SAN MIGUEL Light 330 ml",
        sold: "72",
        price: "344.000",
        discount: "4",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 15,
        image: "for-you/for-you-15",
        title: "Bia Hà Nội Nhãn Xanh - Thùng 24 lon 330ml",
        sold: "64",
        price: "299.000",
        discount: "1",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },

    {
        id: 16,
        image: "for-you/for-you-16",
        title: "BMáy Massage Cầm Tay Cao Cấp KINGTECH KH-720 - 20 Cấp Độ, Hỗ Trợ Mát Xa Chuyên Sâu, Giảm Đau Cơ, Cứng Khớp - Chính Hãng",
        sold: "982",
        price: "1.300.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },

    {
        id: 17,
        image: "for-you/for-you-17",
        title: "Máy Massage Mini Cầm Tay Beurer MG16",
        sold: "61",
        price: "374.000",
        discount: "1",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: true,
        star: 4,
    },

    {
        id: 18,
        image: "for-you/for-you-18",
        title: "Máy Massage Lưng Cao Cấp KINGTECH KB-920 - Mát xa Thắt Lưng, Eo, Cột Sống - Hỗ Trợ Điều Trị Thoát Vị Đĩa Đệm, Thoái Hóa, Đau Đốt Sống, Vai Gáy - Tích Hợp Tính Năng Nhiệt Hồng Ngoại 45 - 65 độ - Hàng Chính Hãng",
        sold: "57",
        price: "1.995.000",
        discount: "40",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },

    {
        id: 19,
        image: "for-you/for-you-19",
        title: "Máy massage cổ FUJITA FH-N289 PLUS thông minh tiện ích thiết kế dễ sử dụng, bền đẹp, phù hợp cho người đau mỏi vai gáy, hoa mắt chóng mặt",
        sold: "33",
        price: "1.190.000",
        discount: "43",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },

    {
        id: 20,
        image: "for-you/for-you-20",
        title: "4 Lốc sữa tươi tiệt trùng TH True Milk Light Meal bổ sung ngũ cốc 180ml (180ml x 4 hộp)",
        sold: "11",
        price: "186.000",
        discount: "3",
        oneLine: false,
        sale: true,
        refund: true,
        ship: true,
        rate: true,
        star: "",
    },

    {
        id: 21,
        image: "for-you/for-you-21",
        title: "Thùng 48 Bịch Sữa Tiệt Trùng Dutch Lady Cô Gái Hà Lan Không Đường (48X220ml)",
        sold: "1000+",
        price: "310.000",
        discount: "26",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },

    {
        id: 22,
        image: "for-you/for-you-22",
        title: "Thùng 48 Hộp Sữa Uống Tiệt Trùng Dutch Lady Cô Gái Hà Lan Dâu (48 x 110ml)",
        sold: "62",
        price: "299.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },

    {
        id: 23,
        image: "for-you/for-you-23",
        title: "Monster #8 - Tập 2",
        sold: "1000+",
        price: "59.000",
        discount: "1",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },

    {
        id: 24,
        image: "for-you/for-you-24",
        title: "Miền Đất Hứa 0 - Mystic Code",
        sold: "624",
        price: "29.000",
        discount: "1",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },

    {
        id: 25,
        image: "for-you/for-you-25",
        title: "Combo Trọn Bộ CONAN ĐẶC SẮC: Conan và Tổ chức Áo Đen (Tập 1, 2) + Conan Tuyển Tập Đặc Biệt - FBI Selection + Conan Tuyển Tập Fan Bình Chọn (Tập 1, 2) + Conan Những Câu Chuyện Lãng Mạn (Tập 1,2,3) - Bộ 8 Cuốn/ Tặng Kèm Postcard Green Life",
        sold: "164",
        price: "269.000",
        discount: "12",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },

    {
        id: 26,
        image: "for-you/for-you-26",
        title: "Boxset Trọn Bộ 21 Tập: Assassination Classroom ( Tặng Poster , Lịch, Sổ Tay )",
        sold: "47",
        price: "899.000",
        discount: "19",
        oneLine: false,
        sale: true,
        refund: true,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 27,
        image: "for-you/for-you-27",
        title: "Thám Tử Lừng Danh Conan: Hồ Sơ Tuyệt Mật - Shuichi Akai & Toru Amuro",
        sold: "633",
        price: "199.000",
        discount: "1",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 28,
        image: "for-you/for-you-28",
        title: "Xe máy điện VinFast Klara A2 - 2021 (Đã bao gồm Sạc & Ắc quy)",
        sold: "1000+",
        price: "26.900.000 ₫",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 29,
        image: "for-you/for-you-29",
        title: "Xe Motor điện VinFast Feliz (Đã bao gồm Sạc & Ắc quy)",
        sold: "1000+",
        price: "24.900.000",
        discount: "1",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 30,
        image: "for-you/for-you-30",
        title: "Súng massage toàn thân OKACHI LUXURY JP-i5 Pro (Viền đen)",
        sold: "64",
        price: "2.299.000",
        discount: "17",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 31,
        image: "for-you/for-you-31",
        title: "Gối Massage Hồng Ngoại RULAX 01 cổ vai gáy tựa lưng đa năng",
        sold: "66",
        price: "699.000",
        discount: "28",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 32,
        image: "for-you/for-you-32",
        title: "Ghế Massage Toàn Thân Công Nghệ Nhật Bản QUEEN CROWN QC-F5",
        sold: "642",
        price: "9.299.000",
        discount: "28",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 33,
        image: "for-you/for-you-33",
        title: "Ghế massage trị liệu toàn thân Toshiko T21",
        sold: "64",
        price: "14.990.000",
        discount: "42",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 34,
        image: "for-you/for-you-34",
        title: "Bàn Phím Cơ Gaming XSmart K80 LED RGB 20 Chế Độ Nháy Cực Đẹp, Phím CƠ Gõ Siêu Đã, Thiết Kế Nhỏ Gọn Dùng Cho Máy Tính, Laptop - Hàng Chính Hãng",
        sold: "32",
        price: "278.000",
        discount: "27",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: 4,
    },
    {
        id: 35,
        image: "for-you/for-you-35",
        title: "Bàn Phím Cơ Máy Tính XSmart K2 Pro Màu Xanh Led RGB, Chuyên Game Blue Switch Có 10 Chế Độ Màu Siêu Đẹp - Hàng Chính Hãng",
        sold: "164",
        price: "499.000",
        discount: "1",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 36,
        image: "for-you/for-you-36",
        title: "Tai nghe chụp tai máy tính XSmart GAMING MC Q9 có đèn LED đổi màu, mic đàm thoại, headphone chơi game trên laptop, pc - Hàng Chính Hãng",
        sold: "174",
        price: "260.000",
        discount: "27",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
]
//* Fake data product market
const allMarket = [
    {
        id: 1,
        image: "market/market-1",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 2,
        image: "market/market-2",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 3,
        image: "market/market-3",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 4,
        image: "market/market-4",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 5,
        image: "market/market-5",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 6,
        image: "market/market-6",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 7,
        image: "market/market-7",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 8,
        image: "market/market-8",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 9,
        image: "market/market-9",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 10,
        image: "market/market-10",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 11,
        image: "market/market-11",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 12,
        image: "market/market-12",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 13,
        image: "market/market-13",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 14,
        image: "market/market-14",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 15,
        image: "market/market-15",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 16,
        image: "market/market-16",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 17,
        image: "market/market-17",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 18,
        image: "market/market-18",
        title: "Đi chợ siêu sale, nhiều ưu đãi hấp dẫn",
        sold: "1000+",
        price: "99.000",
        discount: "10",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
]
//* Fake data product deal
const allDeal = [
    {
        id: 1,
        image: "deal/deal-1",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 2,
        image: "deal/deal-2",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 3,
        image: "deal/deal-3",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 4,
        image: "deal/deal-4",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 5,
        image: "deal/deal-5",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 6,
        image: "deal/deal-6",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 7,
        image: "deal/deal-7",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 8,
        image: "deal/deal-8",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 9,
        image: "deal/deal-9",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 10,
        image: "deal/deal-10",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 11,
        image: "deal/deal-11",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: true,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 12,
        image: "deal/deal-12",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 13,
        image: "deal/deal-13",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 14,
        image: "deal/deal-14",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: true,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 15,
        image: "deal/deal-15",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 16,
        image: "deal/deal-16",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 17,
        image: "deal/deal-17",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 18,
        image: "deal/deal-18",
        title: "Sản phẩm deal siêu hot, khuyến mãi cực sâu tha hồ mua sắm",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: true,
        ship: true,
        rate: true,
        star: "",
    },

]
//* Fake data product promotion
const allPromotion = [
    {
        id: 1,
        image: "promotion/promotion-1",
        title: "Sữa Rửa Mặt Từ Blueberry Innisfree Blueberry Rebalancing 5.5 Cleanser 100ml - 131171581",
        sold: "633",
        price: "129.000",
        discount: "14",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 2,
        image: "promotion/promotion-2",
        title: "Sữa Rửa Mặt Dưỡng Ẩm Từ Olive Innisfree Olive Real Cleansing Foam 150g",
        sold: "1000+",
        price: "184.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: true,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 3,
        image: "promotion/promotion-3",
        title: "Sữa Rửa Mặt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml) chính hãng",
        sold: "1000+",
        price: "95.000",
        discount: "27",
        oneLine: false,
        sale: true,
        refund: true,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 4,
        image: "promotion/promotion-4",
        title: "Sữa Rửa Mặt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (100ml)",
        sold: "207",
        price: "85.000",
        discount: "19",
        oneLine: false,
        sale: true,
        refund: true,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 5,
        image: "promotion/promotion-5",
        title: "Sữa Rửa Mặt Tinh Tế Làm Sạch Và Trắng Da Cải Tiến Với Nghệ Tây Himalaya Herbals (150ml)",
        sold: "211",
        price: "129.000",
        discount: "48",
        oneLine: false,
        sale: false,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 6,
        image: "promotion/promotion-6",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: true,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 7,
        image: "promotion/promotion-7",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: true,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 8,
        image: "promotion/promotion-8",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 9,
        image: "promotion/promotion-9",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 10,
        image: "promotion/promotion-10",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 11,
        image: "promotion/promotion-11",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 12,
        image: "promotion/promotion-12",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 13,
        image: "promotion/promotion-13",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 14,
        image: "promotion/promotion-14",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 15,
        image: "promotion/promotion-15",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 16,
        image: "promotion/promotion-16",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: true,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 17,
        image: "promotion/promotion-17",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 18,
        image: "promotion/promotion-18",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 19,
        image: "promotion/promotion-19",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 20,
        image: "promotion/promotion-20",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 21,
        image: "promotion/promotion-21",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 22,
        image: "promotion/promotion-22",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 23,
        image: "promotion/promotion-23",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 24,
        image: "promotion/promotion-24",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 25,
        image: "promotion/promotion-25",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 26,
        image: "promotion/promotion-26",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 27,
        image: "promotion/promotion-27",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 28,
        image: "promotion/promotion-28",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 29,
        image: "promotion/promotion-29",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 30,
        image: "promotion/promotion-30",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 31,
        image: "promotion/promotion-31",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 32,
        image: "promotion/promotion-32",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 33,
        image: "promotion/promotion-33",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 34,
        image: "promotion/promotion-34",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 35,
        image: "promotion/promotion-35",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },
    {
        id: 35,
        image: "promotion/promotion-35",
        title: "Sữa Rửa Mặt Tạo Bọt Neem Ngừa Mụn Trứng Cá Himalaya Herbals (150ml)",
        sold: "266",
        price: "266.000",
        discount: "48",
        oneLine: false,
        sale: true,
        refund: false,
        ship: false,
        rate: true,
        star: "",
    },

]
//* Fake data product cheap
const allCheap = [
    {
        id: 1,
        image: "cheap/cheap-1",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 2,
        image: "cheap/cheap-2",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 3,
        image: "cheap/cheap-3",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 4,
        image: "cheap/cheap-4",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 5,
        image: "cheap/cheap-5",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 6,
        image: "cheap/cheap-6",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 7,
        image: "cheap/cheap-7",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 8,
        image: "cheap/cheap-8",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 9,
        image: "cheap/cheap-9",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 10,
        image: "cheap/cheap-10",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 11,
        image: "cheap/cheap-11",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 12,
        image: "cheap/cheap-12",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 13,
        image: "cheap/cheap-13",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 14,
        image: "cheap/cheap-14",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 15,
        image: "cheap/cheap-15",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 16,
        image: "cheap/cheap-16",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 17,
        image: "cheap/cheap-17",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 18,
        image: "cheap/cheap-18",
        title: "Sản phẩm rẻ vô đối mua ngay",
        sold: "1000+",
        price: "49.000",
        discount: "30",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },

]
//* Fake data product new
const allNew = [
    {
        id: 1,
        image: "new/new-1",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 2,
        image: "new/new-2",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 3,
        image: "new/new-3",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 4,
        image: "new/new-4",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 5,
        image: "new/new-5",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 6,
        image: "new/new-6",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 7,
        image: "new/new-7",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 8,
        image: "new/new-8",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 9,
        image: "new/new-9",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 10,
        image: "new/new-10",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 11,
        image: "new/new-11",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 12,
        image: "new/new-12",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 13,
        image: "new/new-13",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 14,
        image: "new/new-14",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 15,
        image: "new/new-15",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 16,
        image: "new/new-16",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 17,
        image: "new/new-17",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },
    {
        id: 18,
        image: "new/new-18",
        title: "Sản phẩm mới",
        sold: "1000+",
        price: "49.000",
        discount: "33",
        oneLine: false,
        sale: false,
        refund: false,
        ship: true,
        rate: false,
        star: "",
    },

]
//* Fake data product fashion
const allFashion = [
    {
        id: 1,
        image: "fashion/fashion-1",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 2,
        image: "fashion/fashion-2",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 3,
        image: "fashion/fashion-3",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 4,
        image: "fashion/fashion-4",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 5,
        image: "fashion/fashion-5",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 6,
        image: "fashion/fashion-6",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 7,
        image: "fashion/fashion-7",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 8,
        image: "fashion/fashion-8",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 9,
        image: "fashion/fashion-9",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 10,
        image: "fashion/fashion-10",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 11,
        image: "fashion/fashion-11",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 12,
        image: "fashion/fashion-12",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 13,
        image: "fashion/fashion-13",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 14,
        image: "fashion/fashion-14",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 15,
        image: "fashion/fashion-15",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 16,
        image: "fashion/fashion-16",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 17,
        image: "fashion/fashion-17",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 18,
        image: "fashion/fashion-18",
        title: "Sản phẩm xu hướng thời trang",
        sold: "1000+",
        price: "100.000",
        discount: "13",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },

]
//* Fake data product trending
const allTrending = [
    {
        id: 1,
        image: "trending/trending-1",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 2,
        image: "trending/trending-2",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 3,
        image: "trending/trending-3",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 4,
        image: "trending/trending-4",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 5,
        image: "trending/trending-5",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 6,
        image: "trending/trending-6",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 7,
        image: "trending/trending-7",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 8,
        image: "trending/trending-8",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 9,
        image: "trending/trending-9",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 10,
        image: "trending/trending-10",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 11,
        image: "trending/trending-11",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 12,
        image: "trending/trending-12",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 13,
        image: "trending/trending-13",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 14,
        image: "trending/trending-14",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 15,
        image: "trending/trending-15",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 16,
        image: "trending/trending-16",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 17,
        image: "trending/trending-17",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
    {
        id: 18,
        image: "trending/trending-18",
        title: "Sản phẩm trending",
        sold: "1000+",
        price: "88.000",
        discount: "18",
        oneLine: false,
        sale: true,
        refund: false,
        ship: true,
        rate: true,
        star: "",
    },
]
//* Fake data navigation caetegory suggest
const naviCateSuggest = [
    {
        image: "/suggest/suggest-1",
        title: "Gợi ý dành cho bạn, danh mục hot",
    },
    {
        image: "/suggest/suggest-2",
        title: "Gợi ý dành cho bạn",
    },
    {
        image: "/suggest/suggest-3",
        title: "Gợi ý dành cho bạn",
    },
    {
        image: "/suggest/suggest-4",
        title: "Gợi ý dành cho bạn, danh mục hot",
    },
    {
        image: "/suggest/suggest-5",
        title: "Gợi ý dành cho bạn",
    },
    {
        image: "/suggest/suggest-6",
        title: "Gợi ý dành cho bạn",
    },
    {
        image: "/suggest/suggest-7",
        title: "Gợi ý dành cho bạn",
    },
    {
        image: "/suggest/suggest-8",
        title: "Gợi ý dành cho bạn",
    },
    {
        image: "/suggest/suggest-9",
        title: "Gợi ý dành cho bạn",
    },
    {
        image: "/suggest/suggest-10",
        title: "Gợi ý dành cho bạn danh mục hot",
    },
    {
        image: "/suggest/suggest-11",
        title: "Gợi ý dành cho bạn",
    },
    {
        image: "/suggest/suggest-12",
        title: "Gợi ý dành cho bạn",
    },
    {
        image: "/suggest/suggest-13",
        title: "Gợi ý dành cho bạn",
    },
    {
        image: "/suggest/suggest-14",
        title: "Gợi ý dành cho bạn",
    },
    {
        image: "/suggest/suggest-15",
        title: "Gợi ý dành cho bạn, danh mục hot",
    },
]
//* Fake data product navigation caetegory toy mom and baby
const naviCateToy = [
    {
        image: "/toy/toy-1",
        title: "Đồ chơi mẹ và bé",
    },
    {
        image: "/toy/toy-2",
        title: "Đồ chơi mẹ và bé",
    },
    {
        image: "/toy/toy-3",
        title: "Đồ chơi mẹ và bé",
    },
    {
        image: "/toy/toy-4",
        title: "Đồ chơi mẹ và bé",
    },
    {
        image: "/toy/toy-5",
        title: "Đồ chơi mẹ và bé",
    },
    {
        image: "/toy/toy-6",
        title: "Đồ chơi mẹ và bé",
    },
    {
        image: "/toy/toy-7",
        title: "Đồ chơi mẹ và bé",
    },
    {
        image: "/toy/toy-8",
        title: "Đồ chơi mẹ và bé",
    },
    {
        image: "/toy/toy-9",
        title: "Đồ chơi mẹ và bé",
    },
    {
        image: "/toy/toy-10",
        title: "Đồ chơi mẹ và bé",
    },
    {
        image: "/toy/toy-11",
        title: "Đồ chơi mẹ và bé",
    },
    {
        image: "/toy/toy-12",
        title: "Đồ chơi mẹ và bé",
    },
    {
        image: "/toy/toy-13",
        title: "Đồ chơi mẹ và bé",
    },
    {
        image: "/toy/toy-14",
        title: "Đồ chơi mẹ và bé",
    },
    {
        image: "/toy/toy-15",
        title: "Đồ chơi mẹ và bé",
    },
]
//* Fake data product navigation caetegory market
const naviCateMarket = [
    {
        image: "/market/market-1",
        title: "Thực phẩm an toàn chất lượng",
    },
    {
        image: "/market/market-2",
        title: "Thực phẩm an toàn chất lượng",
    },
    {
        image: "/market/market-3",
        title: "Thực phẩm an toàn chất lượng",
    },
    {
        image: "/market/market-4",
        title: "Thực phẩm an toàn chất lượng",
    },
    {
        image: "/market/market-5",
        title: "Thực phẩm an toàn chất lượng",
    },
    {
        image: "/market/market-6",
        title: "Thực phẩm an toàn chất lượng",
    },
    {
        image: "/market/market-7",
        title: "Thực phẩm an toàn chất lượng",
    },
    {
        image: "/market/market-8",
        title: "Thực phẩm an toàn chất lượng",
    },
    {
        image: "/market/market-9",
        title: "Thực phẩm an toàn chất lượng",
    },
    {
        image: "/market/market-10",
        title: "Thực phẩm an toàn chất lượng",
    },
    {
        image: "/market/market-11",
        title: "Thực phẩm an toàn chất lượng",
    },
    {
        image: "/market/market-12",
        title: "Thực phẩm an toàn chất lượng",
    },
    {
        image: "/market/market-13",
        title: "Thực phẩm an toàn chất lượng",
    },
    {
        image: "/market/market-14",
        title: "Thực phẩm an toàn chất lượng",
    },
    {
        image: "/market/market-15",
        title: "Thực phẩm an toàn chất lượng",
    },
]
//* Fake data product navigation caetegory phone and tablet
const naviCateMt = [
    {
        image: "/mt/mt-1",
        title: "Điện thoại, máy tính bảng",
    },
    {
        image: "/mt/mt-2",
        title: "Điện thoại, máy tính bảng",
    },
    {
        image: "/mt/mt-3",
        title: "Điện thoại, máy tính bảng",
    },
    {
        image: "/mt/mt-4",
        title: "Điện thoại, máy tính bảng",
    },
    {
        image: "/mt/mt-5",
        title: "Điện thoại, máy tính bảng",
    },
    {
        image: "/mt/mt-6",
        title: "Điện thoại, máy tính bảng",
    },
    {
        image: "/mt/mt-7",
        title: "Điện thoại, máy tính bảng",
    },
    {
        image: "/mt/mt-8",
        title: "Điện thoại, máy tính bảng",
    },
    {
        image: "/mt/mt-9",
        title: "Điện thoại, máy tính bảng",
    },
    {
        image: "/mt/mt-10",
        title: "Điện thoại, máy tính bảng",
    },
    {
        image: "/mt/mt-11",
        title: "Điện thoại, máy tính bảng",
    },
    {
        image: "/mt/mt-12",
        title: "Điện thoại, máy tính bảng",
    },
    {
        image: "/mt/mt-13",
        title: "Điện thoại, máy tính bảng",
    },
    {
        image: "/mt/mt-14",
        title: "Điện thoại, máy tính bảng",
    },
    {
        image: "/mt/mt-15",
        title: "Điện thoại, máy tính bảng",
    },
]
//* Fake data product navigation caetegory beautify
const naviCateBeautify = [
    {
        image: "/beautify/beautify-1",
        title: "Làm đẹp, sức khỏe",
    },
    {
        image: "/beautify/beautify-2",
        title: "Làm đẹp, sức khỏe",
    },
    {
        image: "/beautify/beautify-3",
        title: "Làm đẹp, sức khỏe",
    },
    {
        image: "/beautify/beautify-4",
        title: "Làm đẹp, sức khỏe",
    },
    {
        image: "/beautify/beautify-5",
        title: "Làm đẹp, sức khỏe",
    },
    {
        image: "/beautify/beautify-6",
        title: "Làm đẹp, sức khỏe",
    },
    {
        image: "/beautify/beautify-7",
        title: "Làm đẹp, sức khỏe",
    },
    {
        image: "/beautify/beautify-8",
        title: "Làm đẹp, sức khỏe",
    },
    {
        image: "/beautify/beautify-9",
        title: "Làm đẹp, sức khỏe",
    },
    {
        image: "/beautify/beautify-10",
        title: "Làm đẹp, sức khỏe",
    },
    {
        image: "/beautify/beautify-11",
        title: "Làm đẹp, sức khỏe",
    },
    {
        image: "/beautify/beautify-12",
        title: "Làm đẹp, sức khỏe",
    },
    {
        image: "/beautify/beautify-13",
        title: "Làm đẹp, sức khỏe",
    },
    {
        image: "/beautify/beautify-14",
        title: "Làm đẹp, sức khỏe",
    },
    {
        image: "/beautify/beautify-15",
        title: "Làm đẹp, sức khỏe",
    },
]
//* Fake data product navigation caetegory equipment
const naviCtaeEquipment = [
    {
        image: "/equipment/equipment-1",
        title: "Đồ điện gia dụng",
    },
    {
        image: "/equipment/equipment-2",
        title: "Đồ điện gia dụng",
    },
    {
        image: "/equipment/equipment-3",
        title: "Đồ điện gia dụng",
    },
    {
        image: "/equipment/equipment-4",
        title: "Đồ điện gia dụng",
    },
    {
        image: "/equipment/equipment-5",
        title: "Đồ điện gia dụng",
    },
    {
        image: "/equipment/equipment-6",
        title: "Đồ điện gia dụng",
    },
    {
        image: "/equipment/equipment-7",
        title: "Đồ điện gia dụng",
    },
    {
        image: "/equipment/equipment-8",
        title: "Đồ điện gia dụng",
    },
    {
        image: "/equipment/equipment-9",
        title: "Đồ điện gia dụng",
    },
    {
        image: "/equipment/equipment-10",
        title: "Đồ điện gia dụng",
    },
    {
        image: "/equipment/equipment-11",
        title: "Đồ điện gia dụng",
    },
    {
        image: "/equipment/equipment-12",
        title: "Đồ điện gia dụng",
    },
    {
        image: "/equipment/equipment-13",
        title: "Đồ điện gia dụng",
    },
    {
        image: "/equipment/equipment-14",
        title: "Đồ điện gia dụng",
    },
    {
        image: "/equipment/equipment-15",
        title: "Đồ điện gia dụng",
    },
]
//* Fake data product navigation caetegory head phone
const naviCateHeadphone = [
    {
        image: "/headphone/headphone-1",
        title: "Tai nghe, phụ kiện",
    },
    {
        image: "/headphone/headphone-2",
        title: "Tai nghe, phụ kiện",
    },
    {
        image: "/headphone/headphone-3",
        title: "Tai nghe, phụ kiện",
    },
    {
        image: "/headphone/headphone-4",
        title: "Tai nghe, phụ kiện",
    },
    {
        image: "/headphone/headphone-5",
        title: "Tai nghe, phụ kiện",
    },
    {
        image: "/headphone/headphone-6",
        title: "Tai nghe, phụ kiện",
    },
    {
        image: "/headphone/headphone-7",
        title: "Tai nghe, phụ kiện",
    },
    {
        image: "/headphone/headphone-8",
        title: "Tai nghe, phụ kiện",
    },
    {
        image: "/headphone/headphone-9",
        title: "Tai nghe, phụ kiện",
    },
    {
        image: "/headphone/headphone-10",
        title: "Tai nghe, phụ kiện",
    },
    {
        image: "/headphone/headphone-11",
        title: "Tai nghe, phụ kiện",
    },
    {
        image: "/headphone/headphone-12",
        title: "Tai nghe, phụ kiện",
    },
    {
        image: "/headphone/headphone-13",
        title: "Tai nghe, phụ kiện",
    },
    {
        image: "/headphone/headphone-14",
        title: "Tai nghe, phụ kiện",
    },
    {
        image: "/headphone/headphone-15",
        title: "Tai nghe, phụ kiện",
    },
]
//* RENDER VIEW PRODUCT
const allSuggest = document.querySelectorAll(".product-head__item")
const suggestMarket = document.querySelector(".product-head__item--market")
const suggestForYou = document.querySelector(".product-head__item--you")
const suggestDeal = document.querySelector(".product-head__item--deal")
const suggestCheap = document.querySelector(".product-head__item--cheap")
const suggestNew = document.querySelector(".product-head__item--new")
const suggestFashion = document.querySelector(".product-head__item--fashion")
const suggestTrending = document.querySelector(".product-head__item--trending")
const suggestPromotion = document.querySelector(".product-head__item--promotion")
const productList = document.querySelector(".product-list")
const allNavigationSuggest = document.querySelectorAll(".navigation-left__item")
const listNavigationCate = document.querySelector(".navigation-right__list")
const titleNaviCateHead = document.querySelector(".navigation-right__title")

window.onload = function (e) {
    renderViewProduct(allForYou)
}

function renderViewProduct(listProducts) {
    const htmls = listProducts.map(item => {
        return `
        <li class="product-item
        ${item.oneLine === true ? "one-line" : ""}
        ${item.sale === true ? "sale" : ""}
        ${item.refund === true ? "refund" : ""}
        ${item.ship === true ? "ship" : ""}
        ${item.rate === true ? "rate" : ""}
        ${item.star === 1 ? "star-1" : item.star === 2 ? "star-2" : item.star === 3 ? "star-3" : item.star === 4 ? "star-4" : ""}
        ">
            <div class="product-item__head">
                <img src="./image/product/${item.image}.webp" alt="product" class="product-item__img">
                 <img src="./image/product/freeship.png" alt="freeship" class="product-item__lable">
                    </div>
                        <div class="product-item__content">
                            <h5>${item.title}</h5>
                            <div class="product-item__rate">
                                <div class="product-item__star">
                                    <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24"
                                        size="14" color="#fdd836" height="14" width="14"
                                        xmlns="http://www.w3.org/2000/svg" style="color: rgb(253, 216, 54);">
                                        <path class="product-item__star__icon product-item__star__icon--1"
                                            d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z">
                                        </path>
                                    </svg>
                                    <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24"
                                        size="14" color="#fdd836" height="14" width="14"
                                        xmlns="http://www.w3.org/2000/svg" style="color: rgb(253, 216, 54);">
                                        <path class="product-item__star__icon product-item__star__icon--2"
                                            d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z">
                                        </path>
                                    </svg>
                                    <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24"
                                        size="14" color="#fdd836" height="14" width="14"
                                        xmlns="http://www.w3.org/2000/svg" style="color: rgb(253, 216, 54);">
                                        <path class="product-item__star__icon product-item__star__icon--3"
                                            d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z">
                                        </path>
                                    </svg>
                                    <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24"
                                        size="14" color="#fdd836" height="14" width="14"
                                        xmlns="http://www.w3.org/2000/svg" style="color: rgb(253, 216, 54);">
                                        <path class="product-item__star__icon product-item__star__icon--4"
                                            d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z">
                                        </path>
                                    </svg>
                                    <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24"
                                        size="14" color="#fdd836" height="14" width="14"
                                        xmlns="http://www.w3.org/2000/svg" style="color: rgb(253, 216, 54);">
                                        <path class="product-item__star__icon product-item__star__icon--5"
                                            d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z">
                                        </path>
                                    </svg>
                                </div>
                                <span class="product-item__amount">Đã bán ${item.sold}</span>
                            </div>
                            <div class="product-item__bottom">
                                <h4 class="product-item__price">${item.price} ₫</h4>
                                <span class="product-item__discount">-${item.discount}%</span>
                            </div>
                        </div>
                    <div class="product-item__refund">
                <img src="./image/product/refund.png" alt="refund">
            </div>
        </li>
        `

    })
    productList.innerHTML = htmls.join("");
}

//* Click suggest show product
allSuggest.forEach(item => {
    item.addEventListener("click", (e) => {
        allSuggest.forEach(item => item.classList.remove("active"))
        item.classList.add("active")
        const cls = item.classList;
        switch (true) {
            case cls.contains("for-you"):
                renderViewProduct(allForYou)
                break;
            case cls.contains("market"):
                renderViewProduct(allMarket)
                break;
            case cls.contains("deal"):
                renderViewProduct(allDeal)
                break;
            case cls.contains("cheap"):
                renderViewProduct(allCheap)
                break;
            case cls.contains("new"):
                renderViewProduct(allNew)
                break;
            case cls.contains("fashion"):
                renderViewProduct(allFashion)
                break;
            case cls.contains("trending"):
                renderViewProduct(allTrending)
                break;
            case cls.contains("promotion"):
                renderViewProduct(allPromotion)
                console.log(111)
                break;
            default:
                break;
        }
    })
})
//* Navigation category product
allNavigationSuggest.forEach(item => {
    item.addEventListener("click", (e) => {
        allNavigationSuggest.forEach(item => item.classList.remove("active"))
        item.classList.add("active")
        const cls = item.classList
        const title = item.querySelector("span")
        switch (true) {
            case cls.contains("navigation-suggest"):
                renderViewNaviCate(naviCateSuggest)
                titleNaviCateHead.textContent = title.textContent
                break;
            case cls.contains("navigation-toy"):
                renderViewNaviCate(naviCateToy)
                titleNaviCateHead.textContent = title.textContent
                break;
            case cls.contains("navigation-market"):
                renderViewNaviCate(naviCateMarket)
                titleNaviCateHead.textContent = title.textContent
                break;
            case cls.contains("navigation-mt"):
                renderViewNaviCate(naviCateMt)
                titleNaviCateHead.textContent = title.textContent
                break;
            case cls.contains("navigation-beautify"):
                renderViewNaviCate(naviCateBeautify)
                titleNaviCateHead.textContent = title.textContent
                break;
            case cls.contains("navigation-equipment"):
                renderViewNaviCate(naviCtaeEquipment)
                titleNaviCateHead.textContent = title.textContent
                break;
            case cls.contains("navigation-headphone"):
                renderViewNaviCate(naviCateHeadphone)
                titleNaviCateHead.textContent = title.textContent
                break;
        }
    })
})

function renderViewNaviCate(allProducts) {
    const htmls = allProducts.map(item => {
        return `
        <li class="navigation-right__item">
              <img src="./image/navigation/${item.image}.webp" alt="product">
              <span>${item.title}</span>
        </li>
        `
    })
    listNavigationCate.innerHTML = htmls.join("")
}

//* Render default view product navigation category suggest
document.querySelector(".navigation-category").addEventListener("click", (e) => {
    renderViewNaviCate(naviCateSuggest)
})